env:
  global:
   CC_TEST_REPORTER_ID=1a329d3252cc729376937fb3b4922c017f1e9e27e45a1c1cd456182525d2a0fa
   
language: ruby

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

rvm:
  - 2.5.7
  - 2.6.3

script:
  - bundle exec rake spec
  - bundle exec rake minitest

after_script:            
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT